### ISSUE TITLE
Лишнее

### ISSUE THREAD

**Issue by PhoenixNazarov** [mgvts/RISC#2]
Этот файл тут совсем не кстати [ _\_init\__.py](https://github.com/mgvts/RISC/blob/master/__init__.py). Советую удалить его

**Comment by PhoenixNazarov** [comment]
Папку .idea следует добавить в .gitignore и удалить с реаозитория. Потому что, когда несколько яеловек работают над проектом. После загрузки репозитория, у них будет ломаться проект в ide.

**Comment by mgvts** [comment]
well
